export const ACTIONS = {
  LOGIN: {
    ATTEMPT: 'LOGIN:ATTEMPT',
    SUCCESS: 'LOGIN:SUCCESS',
    COMPLETE: 'LOGIN:COMPLETE',
    FAILED: 'LOGIN:FAILED'
  },
  DEVICE: {
    ATTEMPT: 'DEVICE:ATTEMPT',
    SUCCESS: 'DEVICE:SUCCESS',
    FAILED: 'DEVICE:FAILED'
  },
  USER: {
    ATTEMPT: 'USER:ATTEMPT',
    SUCCESS: 'USER:SUCCESS',
    FAILED: 'USER:FAILED'
  },
  ORGANISATION: {
    ATTEMPT: 'ORGANISATION:ATTEMPT',
    SUCCESS: 'ORGANISATION:SUCCESS',
    FAILED: 'ORGANISATION:FAILED'
  },
  ROUTING_STATUS: {
    ATTEMPT: 'ROUTING_STATUS:ATTEMPT',
    SUCCESS: 'ROUTING_STATUS:SUCCESS',
    OPLOG: 'ROUTING_STATUS:OPLOG',
    FAILED: 'ROUTING_STATUS:FAILED'
  },
  ROUTING_STATUS_ACTIVITY: {
    ATTEMPT: 'ROUTING_STATUS_ACTIVITY:ATTEMPT',
    SUCCESS: 'ROUTING_STATUS_ACTIVITY:SUCCESS',
    OPLOG: 'ROUTING_STATUS_ACTIVITY:OPLOG',
    FAILED: 'ROUTING_STATUS_ACTIVITY:FAILED'
  },
  MEMBER_ACTIVITY: {
    ATTEMPT: 'MEMBER_ACTIVITY:ATTEMPT',
    SUCCESS: 'MEMBER_ACTIVITY:SUCCESS',
    OPLOG: 'MEMBER_ACTIVITY:OPLOG',
    FAILED: 'MEMBER_ACTIVITY:FAILED'
  },
  INTERACTION_FLOWS: {
    ATTEMPT: 'INTERACTION_FLOWS:ATTEMPT',
    SUCCESS: 'INTERACTION_FLOWS:SUCCESS',
    OPLOG: 'INTERACTION_FLOWS:OPLOG',
    FAILED: 'INTERACTION_FLOWS:FAILED'
  },
  SELECTED_PRESENCE: {
    ATTEMPT: 'SELECTED_PRESENCE:ATTEMPT',
    SUCCESS: 'SELECTED_PRESENCE:SUCCESS',
    OPLOG: 'SELECTED_PRESENCE:OPLOG',
    FAILED: 'SELECTED_PRESENCE:FAILED'
  },
  PRESENCES: {
    ATTEMPT: 'PRESENCES:ATTEMPT',
    SUCCESS: 'PRESENCES:SUCCESS',
    FAILED: 'PRESENCES:FAILED'
  },
  ACTIVE_INTERACTIONS: {
    ATTEMPT: 'ACTIVE_INTERACTIONS:ATTEMPT',
    SUCCESS: 'ACTIVE_INTERACTIONS:SUCCESS',
    OPLOG: 'ACTIVE_INTERACTIONS:OPLOG',
    FAILED: 'ACTIVE_INTERACTIONS:FAILED'
  },
  FEATURE_FLAGS: {
    AUTO_ANSWER: {
      SUCCESS: 'FEATURE_FLAG:AUTO_ANSWER:SUCCESS',
      FAILED: 'FEATURE_FLAG:AUTO_ANSWER:FAILED'
    },
    INCOMING_CALL_POP: {
      SUCCESS: 'FEATURE_FLAG:INCOMING_CALL_POP:SUCCESS',
      FAILED: 'FEATURE_FLAG:INCOMING_CALL_POP:FAILED'
    },
    SHARED_LOGOUT: {
      SUCCESS: 'FEATURE_FLAG:SHARED_LOGOUT:SUCCESS',
      FAILED: 'FEATURE_FLAG:SHARED_LOGOUT:FAILED'
    },
    LOGS: {
      SUCCESS: 'FEATURE_FLAG:LOGS:SUCCESS',
      FAILED: 'FEATURE_FLAG:LOGS:FAILED'
    },
    FORCED_LOGS: {
      SUCCESS: 'FEATURE_FLAG:FORCED_LOGS:SUCCESS',
      FAILED: 'FEATURE_FLAG:FORCED_LOGS:FAILED'
    }
  },
  VOLUME: 'VOLUME:CHANGE',
  SETTINGS: 'VOLUME:SETTINGS',
  END_WRAPUP: {
    ATTEMPT: 'END_WRAPUP:ATTEMPT'
  },

  OPLOG: {
    ATTEMPT: 'OPLOG:ATTEMPT',
    SUCCESS: 'OPLOG:SUCCESS',
    FAILED: 'OPLOG:FAILED',
    RECONNECT: 'OPLOG:RECONNECT'
  },
  SIP: {
    RECONNECT: 'SIP:RECONNECT',
    CONNECTING: 'SIP:CONNECTING',
    CONNECTED: 'SIP:CONNECTED',
    DISCONNECTED: 'SIP:DISCONNECTED',
    FAILED: 'SIP:FAILED',
    CALL: {
      ANSWERED: 'SIP:CALL:ANSWERED',
      NOTIFIED: 'SIP:CALL:NOTIFIED',
      CONNECTING: 'SIP:CALL:CONNECTING',
      SENDING: 'SIP:CALL:SENDING',
      PROGRESS: 'SIP:CALL:PROGRESS',
      ACCEPTED: 'SIP:CALL:ACCEPTED',
      CONFIRMED: 'SIP:CALL:CONFIRMED',
      ENDED: 'SIP:CALL:ENDED',
      FAILED: 'SIP:CALL:FAILED',
      HOLD: 'SIP:CALL:HOLD',
      UNHOLD: 'SIP:CALL:UNHOLD',
      MUTED: 'SIP:CALL:MUTED',
      UNMUTED: 'SIP:CALL:UNMUTED'
    }
  },
  ERROR: {
    MEDIA_DEVICE: 'ERROR:MEDIA_DEVICE',
    MEDIA_DEVICE_CHANGE: 'ERROR:MEDIA_DEVICE_CHANGE',
    INCOMING_CALL_POP: 'ERROR:INCOMING_CALL_POP',
  },
  UA: {
    REGISTERED: 'UA:REGISTERED',
    UNREGISTERED: 'UA:UNREGISTERED',
    FAILED: 'UA:FAILED',
  },

  LOG: {
    INFO: 'LOG:INFO',
    ERROR: 'LOG:ERROR',
    AUDIT: 'LOG:AUDIT'
  },
  VERSION: {
    SUCCESS: 'VERSION:SUCCESS',
    OPLOG: 'VERSION:OPLOG'
  }
};
